"""Initial migration - create all tables

Revision ID: 49276bf7c3fa
Revises: 
Create Date: 2026-01-27 11:23:23.970595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49276bf7c3fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('endereco', sa.JSON(), nullable=True),
    sa.Column('role', sa.Enum('EMPREENDEDOR', 'GESTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cnpj'), 'users', ['cnpj'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_razao_social'), 'users', ['razao_social'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('applicant_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANALISE', 'PENDENCIA', 'VISTORIA', 'EMITIDO', 'INDEFERIDO', name='processstatus'), nullable=False),
    sa.Column('deadline_agency', sa.Date(), nullable=True),
    sa.Column('deadline_applicant', sa.Date(), nullable=True),
    sa.Column('process_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_activity_id'), 'processes', ['activity_id'], unique=False)
    op.create_index(op.f('ix_processes_applicant_id'), 'processes', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_processes_created_at'), 'processes', ['created_at'], unique=False)
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_index(op.f('ix_processes_status'), 'processes', ['status'], unique=False)
    op.create_table('process_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_documents_id'), 'process_documents', ['id'], unique=False)
    op.create_index(op.f('ix_process_documents_process_id'), 'process_documents', ['process_id'], unique=False)
    op.create_table('process_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_history_created_at'), 'process_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_history_id'), 'process_history', ['id'], unique=False)
    op.create_index(op.f('ix_process_history_process_id'), 'process_history', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_history_process_id'), table_name='process_history')
    op.drop_index(op.f('ix_process_history_id'), table_name='process_history')
    op.drop_index(op.f('ix_process_history_created_at'), table_name='process_history')
    op.drop_table('process_history')
    op.drop_index(op.f('ix_process_documents_process_id'), table_name='process_documents')
    op.drop_index(op.f('ix_process_documents_id'), table_name='process_documents')
    op.drop_table('process_documents')
    op.drop_index(op.f('ix_processes_status'), table_name='processes')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_created_at'), table_name='processes')
    op.drop_index(op.f('ix_processes_applicant_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_activity_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_users_razao_social'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cnpj'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
